# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "A Spotify CLI"
  homepage "https://github.com/matthew-collett/sp"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthew-collett/sp/releases/download/v0.5.0/sp_darwin_amd64.tar.gz"
      sha256 "ad1e58561fcb0399e4784fe30cab426304ac8b807e958856bd22980f75a503c5"

      define_method(:install) do
        bin.install "sp"
        generate_completions_from_executable(bin/"sp", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthew-collett/sp/releases/download/v0.5.0/sp_darwin_arm64.tar.gz"
      sha256 "e249afd00b12ff940cad3d260fc0e81c8d548ee94fbf946a239826dce0b15a44"

      define_method(:install) do
        bin.install "sp"
        generate_completions_from_executable(bin/"sp", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthew-collett/sp/releases/download/v0.5.0/sp_linux_amd64.tar.gz"
      sha256 "b8683f21fa6f68094d93b03b337502ba4deefbf3eed604788c4b155fc9ae8575"
      define_method(:install) do
        bin.install "sp"
        generate_completions_from_executable(bin/"sp", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthew-collett/sp/releases/download/v0.5.0/sp_linux_arm64.tar.gz"
      sha256 "e2673e225c58ba14906c95e4c05e21dfdf2e5169688eff030fd1e4917e8a9ef2"
      define_method(:install) do
        bin.install "sp"
        generate_completions_from_executable(bin/"sp", "completion")
      end
    end
  end

  test do
    system "#{bin}/sp", "--version"
  end
end
