# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "A fast, minimal Spotify CLI and MCP server for your terminal"
  homepage "https://github.com/matthew-collett/sp"
  version "0.9.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.8/sp_darwin_amd64.tar.gz"
      sha256 "1e78e372fb6c1ab988a66d2248e8cf53154a4437b293ef6dca9956a24a50266f"

      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.8/sp_darwin_arm64.tar.gz"
      sha256 "4f9cd5889c04421fda0bbe819ad3ed0087e20070ec4b2dd5a419b5128bcc44b0"

      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.8/sp_linux_amd64.tar.gz"
      sha256 "294ecd1d9db174be3dec3c9532995688ab740bc0bf6aae22da7f5d40e363b612"
      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.8/sp_linux_arm64.tar.gz"
      sha256 "e484daa0f69b78da177993ec7d61cfd2b17ff60b2be12e9869e602a2fc426cff"
      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/sp", "--version"
  end
end
