# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "A fast, minimal Spotify CLI and MCP server for your terminal"
  homepage "https://github.com/matthew-collett/sp"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.0/sp_darwin_amd64.tar.gz"
      sha256 "bebed6e95e12dcc139ae6d8999bc2ba521d1626320baf2edd24f9aeaa3421c97"

      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.0/sp_darwin_arm64.tar.gz"
      sha256 "5bbe3a1430f64671f42ca30a7248be407c96f6c0e11746d932446ed417270945"

      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.0/sp_linux_amd64.tar.gz"
      sha256 "8359d4caadaa85383ba669c6298be1ba7073392ebfc019a32b09d194cc37f993"
      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matthew-collett/sp/releases/download/v0.9.0/sp_linux_arm64.tar.gz"
      sha256 "0795a4a29f63b2fa0d99906791d5bfc0cdf6ad6fb198341e58cdf5025a45f142"
      define_method(:install) do
        bin.install "sp"
        bin.install "sp-mcp"
        generate_completions_from_executable(bin/"sp", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/sp", "--version"
  end
end
