# This file was generated by GoReleaser. DO NOT EDIT.
cask "sp" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "30d220c2e600e1594e9ddfeef0c0cd1da380ddebb2bfe83475f77ec93c44c987"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "871783ee5dc022ca714f07e740123e3f3fd296e979b132be1a4a427a215f2c02"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3995f59755a03f56791f80ff0046dc991e605264e2cb610404a4fc83dfc900c"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "62f58e2acab14238c52c3ba945d7ffa5d8a00399328d9f27e9a909712e85f1f3"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_linux_arm64.tar.gz"
    end
  end

  name "sp"
  desc "A fast, minimal Spotify CLI and MCP server for your terminal"
  homepage "https://github.com/matthew-collett/sp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sp"

  generate_completions_from_executable "bin/sp", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
