# This file was generated by GoReleaser. DO NOT EDIT.
cask "sp" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "fcba6d790f9c7408bc2587b744599ab271b62712e9e43b6c84d26bb162e2b836"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6089dbac1559e213cc4cb7ba8360a68c0fa5b0181510c0c828b84eb268e5401"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "93af793ac3d178c3d28333cf1d9b550620da96985d5bbb2cb5ac8557f3ff7150"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9ef1dad252b11b55ad99212c06ae090e49cbe427477b30b5c0e1225bee58355f"
      url "https://github.com/matthew-collett/sp/releases/download/v#{version}/sp_linux_arm64.tar.gz"
    end
  end

  name "sp"
  desc "A fast, minimal Spotify CLI and MCP server for your terminal"
  homepage "https://github.com/matthew-collett/sp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sp"
  binary "sp-mcp"

  generate_completions_from_executable "bin/sp", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
